[[section-system-scope-and-context]]
== Alcance y contexto del sistema

=== Contexto de negocio

La aplicación web permitirá a los usuarios iniciar sesión con su cuenta de un proveedor de pods (solidcommunity o inrupt). Además, una
vez el usuario ha iniciado sesión en la web podrá ver sus amigos y añadir nuevos o eliminar los ya añadidos. Toda la información de los 
amigos se almacenará en el pod del usuario. Además desde la aplicación web se podrá visualizar las localizaciones de los amigos cercanos y 
se podrá interactuar con ellos desde el chat en tiempo real.
 +
 + 
Por otro lado la aplicación móvil tendrá un inicio de sesión identico de cara al usuario, aunque internamente la aplicación hará una petición
al servidor para que este inicie sesión en su lugar. Con una sesión iniciada el usuario podrá activar la geolocalización para enviar localizaciones y 
podrá ver sus datos de perfil, además de pdoer acceder a la lista de amigos y interactuar con ellos usando el chat. El contenido del chat será igual tanto 
para la aplicación web como para la móvil.


=== Contexto Técnico

Como hemos comentado nuestro sistema está basado en SOLID, el cuál nos permite la descentralización de la web.Así mismo nos suministra el llamado POD;
dicho POD nos permite guardar información, como por ejemplo almacenar la localización del usuario de manera segura.
Por otro lado, cada usuario tendrá un POD individualizado.

Todo esto estará integrado a través del framework React, el cuál es una librería de JavaScript, que nos facilita y permite construir la interfaz de usuario.

[%header,cols="2*"]
|===
|Interfaz técnica|Descripción
| _Solid_ | Base general de la aplicación
| _POD_ | Cada uno de estos usuarios posee un POD, que mantiene la información de este
| _React_ | Permite generar la interfaz de la aplicación web
| _React Native_ | Permite generar la interfaz de la aplicación móvil
|===

