[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Escenario 1: peticion de ubicación


* El usuario 1 accede a la ubicación del usuario 2 y posteriormente el usuario 2 accede a la del 1.
* Tras la peticion del usuario 1 por la ubicacion del usuario 2, se recive una respuesta con la ubicacion y posteriormente se almacena la ubicación en el pod del usuario 2. Lo mismo ocurre cuando el usuario 2 lleva a cabo la petición por la ubicación del usuario 1.

El diagrama de secuencia es el siguiente:

[plantuml,"Sequence diagram",png]
----
actor "Usuario 1"
actor "Usuario 2"
database Pod as "Pod de Usuario 1"
database Pod2 as "Pod de Usuario 2"
"Usuario 1" -> "Usuario 2": Solicita ubicación
"Usuario 2" --> "Usuario 1": Se responde a la petición
"Usuario 1"  --> Pod2: Se almacena la ubicación
"Usuario 2" -> "Usuario 1": Solicita ubicación
"Usuario 2" <-- "Usuario 1": Se responde a la petición
"Usuario 2"  --> Pod: Se almacena la ubicación
----