[[section-runtime-view]]
== Vista en tiempo de ejecución

=== Escenario 1: Inicio de sesión válido

* El usuario desea iniciar sesión con su cuenta de Solid.
* Una vez el usuario ha introducido sus credenciales y ha pulsado el botón de iniciar sesión, la aplicación móvil 
realizará una petición al servidor en la que enviará las credenciales del usuario. 
* El servidor recibirá la petición y usando las credenciales del usuario intentará iniciar sesión en el pod del usuario.
* El servidor responderá a la petición con el resultado del inicio de sesión. En caso de que el inicio fuese válido, la aplicación móvil 
realizará otra petición al servidor en la que solicitará la información personal del usuario. Dicha información será obtenida por el servidor 
a través del pod el usuario.

El diagrama de secuencia es el siguiente:

[plantuml,"Sequence diagram",png]
----
actor Usuario as "Usuario"
entity App as "RADARIN App"
database Server as "Servidor RADARIN"
database Pod as "Pod del Usuario"
Usuario -> App: Introduce credenciales
Usuario -> App: Intenta iniciar sesión
App -> Server: Se envía petición para iniciar sesión
Server -> Pod: Se envía petición para iniciar sesión
Pod --> Server: Se devuelve el resultado del inicio de sesión
Server --> App: Se devuelve el resultado del inicio de sesión
App -> App: Se evalúa resultado del inicio de sesión
App -> Server: Se envía petición para obtener información personal
Server -> Pod: Se envía petición para obtener información personal
Pod --> Server: Se devuelve el resultado de la consulta
Server --> App: Se devuelve el resultado de la consulta
App -> Usuario: Se muestra el inicio de sesión correcto
App -> Usuario: Se visualiza la información personal
----

=== Escenario 2: Notificación amigo cerca


* Proceso para que un usario sea notificado de que un amigo esta cerca suyo.
* Para que un usuario pueda ser notificado de que un amigo suyo se encuentra cerca de su posición este primero debe activar la
geolocalización en la pestaña de ajustes de la aplicación.
* Una vez activada la geolocalización, la aplicación envia una petición al servidor donde incluye las coordenadas del usuario.
* El servidor recibe dicha petición, almacena las coordenadas del usuario y comprueba que amigos de ese usuario se encuentran 
cerca de su posición en base a las ultimas coordenadas de cada uno.
* El servidor responde a la petición de la aplicación móvil con el numero de amigos cerca de su posición, y en caso de que este 
número sea mayor de 0, también se enviará una lista de qué amigos son aquellos que se encuentran cerca.
* Si el usuario ha activado las notificaciones en los ajustes de la aplicación (por defecto esta opción ya se encuentra activada), 
cuando se reciba la respuesta del servidor se lanzará una notificación, si la aplicación se encuentra en segundo plano. Además se 
podrá visualizar dichos avisos desde la ventana de avisos de la aplicación.

El diagrama de secuencia es el siguiente:
 
[plantuml,"Sequence diagram 2",png]
----
actor Usuario
entity App as "RADARIN App"
database Server as "Servidor RADARIN"
Usuario -> App: Inicia la aplicación
Usuario -> App: Activa la geolocalización
App -> Server: Se envía petición para guardar coordenadas
Server -> Server: Se almacena la localización
Server -> Server: Se comprueba los amigos cercanos al usuario
Server --> App: Se devuelve el resultado con el número de amigos cerca
App -> App: Comprueba que el número de amigos cerca no es 0
App -> App: Comprueba que la aplicación está en segundo plano
App --> Usuario: Se lanza notificación
Usuario -> App: Accede a la aplicación
Usuario -> App: Accede a la vista de avisos
App --> Usuario: Se visualiza la lista de avisos

----

=== Escenario 3: Enviar mensaje de chat desde el móvil


* Proceso para que un usario envia un mensaje a uno de sus amigos desde la aplicación móvil.
* El usuario accede a la lista de amigos. La aplicación recuperará los mensajes haciendo una petición al servidor.
* Los mensajes serán mostrados al usuario en la vista de la aplicación móvil. A su vez, la aplicación arrancará una tarea asincrona que
recargará los mensajes cada 2 segundos.
* Cuando un usuario escriba un mensaje este se almacenará para luego ser enviado al servidor y que este lo almacene.

El diagrama de secuencia es el siguiente:
 
[plantuml,"Sequence diagram 2",png]
----
actor Usuario
entity App as "RADARIN App"
database Server as "Servidor RADARIN"
Usuario -> App: Accede a lista de amigos
App --> Usuario: Se visualiza la lista
Usuario -> App: Selecciona un amigo
App -> Server: Se solicita la lista de mensajes entre esos dos usuarios
Server --> App: Se devuelve la lista de mensajes entre esos dos usuarios
App -> App: Se inicia la recarga de mensajes en segundo plano
App --> Usuario: Se muestran los mensajes
Usuario -> App: Escribe un mensaje
App -> App: Se almacena el mensaje
Usuario -> App: Envia el mensaje
App -> Server: Se envia el mensaje para que se guarde
Usuario -> App: Sale del chat
App -> App: Se detiene la recarga de mensajes
App --> Usuario: Se vuelve a visualizar la lista de amigos

----