[[section-design-decisions]]
== Decisiones de Diseño

[%header,cols="2*"]
|===
|Decisión|Descripción      
|*React*| Es la libreria de javascrit que elegimos para desarrollar las interfaces de usuario.
| *Pods*| Aquí se almacenaran los datos de registro(nombre, apellidos...) y amigos.
|*GitHub*| Aquí es donde se ubica el repositorio del proyecto.
|*Mongo*| Es una bases de datos donde vamos a almacenar las rutas y un identificador del pod.
|*Arc42*| Proporciona una  plantilla de documentación y comunicación para el desarrollo del proyecto.
|==

[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
